#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/output/site"
TERRAIN_OUT="$ROOT/output/terrain"
MOONBOOK_OUT="$ROOT/output/moonbook"
MOONCLAW_OUT="$ROOT/output/moonclaw"
MOONROBO_OUT="$ROOT/output/moonrobo"
UI_OUT="$ROOT/output/ui"
RABBITA_OUT="$UI_OUT/rabbita"

mkdir -p "$OUT"
mkdir -p "$TERRAIN_OUT"
mkdir -p "$MOONBOOK_OUT"
mkdir -p "$MOONCLAW_OUT"
mkdir -p "$MOONROBO_OUT"
mkdir -p "$UI_OUT"
mkdir -p "$RABBITA_OUT"

cd "$ROOT"

bash scripts/verify_moonmoon_sources.sh
python3 scripts/compute_power_window.py --check
python3 scripts/generate_moonmoon_fixture.py
python3 scripts/generate_corridor_scan.py
python3 scripts/generate_power_window.py

/Users/kq/.moon/bin/moon run cmd/main > "$OUT/first_trusted_square.md"
/Users/kq/.moon/bin/moon run cmd/main -- json > "$OUT/first_trusted_square.json"
/Users/kq/.moon/bin/moon run cmd/main -- terrain fixture > "$TERRAIN_OUT/first_trusted_square_grid.md"
/Users/kq/.moon/bin/moon run cmd/main -- terrain fixture json > "$TERRAIN_OUT/first_trusted_square_grid.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonbook dossier > "$MOONBOOK_OUT/first_trusted_square_book.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonbook dossier json > "$MOONBOOK_OUT/first_trusted_square_book.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw proposals > "$MOONCLAW_OUT/first_trusted_square_proposals.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw proposals json > "$MOONCLAW_OUT/first_trusted_square_proposals.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw ephemeris tasks > "$MOONCLAW_OUT/first_trusted_square_ephemeris_tasks.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw ephemeris tasks json > "$MOONCLAW_OUT/first_trusted_square_ephemeris_tasks.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw corridor tasks > "$MOONCLAW_OUT/first_trusted_square_corridor_tasks.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw corridor tasks json > "$MOONCLAW_OUT/first_trusted_square_corridor_tasks.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw receipts > "$MOONCLAW_OUT/first_trusted_square_receipts.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw receipts json > "$MOONCLAW_OUT/first_trusted_square_receipts.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw ephemeris receipts > "$MOONCLAW_OUT/first_trusted_square_ephemeris_receipts.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw ephemeris receipts json > "$MOONCLAW_OUT/first_trusted_square_ephemeris_receipts.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw corridor receipts > "$MOONCLAW_OUT/first_trusted_square_corridor_receipts.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonclaw corridor receipts json > "$MOONCLAW_OUT/first_trusted_square_corridor_receipts.json"
/Users/kq/.moon/bin/moon run cmd/main -- moonrobo handoff > "$MOONROBO_OUT/first_trusted_square_handoffs.md"
/Users/kq/.moon/bin/moon run cmd/main -- moonrobo handoff json > "$MOONROBO_OUT/first_trusted_square_handoffs.json"
/Users/kq/.moon/bin/moon run cmd/main -- ui view > "$UI_OUT/first_trusted_square_view.md"
/Users/kq/.moon/bin/moon run cmd/main -- ui view json > "$UI_OUT/first_trusted_square_view.json"
/Users/kq/.moon/bin/moon run cmd/main -- ui rabbita > "$RABBITA_OUT/first_trusted_square.html"
python3 scripts/materialize_moonbook_workspace.py

printf 'wrote %s\n' "$OUT/first_trusted_square.md"
printf 'wrote %s\n' "$OUT/first_trusted_square.json"
printf 'wrote %s\n' "$TERRAIN_OUT/first_trusted_square_grid.md"
printf 'wrote %s\n' "$TERRAIN_OUT/first_trusted_square_grid.json"
printf 'wrote %s\n' "$MOONBOOK_OUT/first_trusted_square_book.md"
printf 'wrote %s\n' "$MOONBOOK_OUT/first_trusted_square_book.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_proposals.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_proposals.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_ephemeris_tasks.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_ephemeris_tasks.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_corridor_tasks.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_corridor_tasks.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_receipts.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_receipts.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_ephemeris_receipts.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_ephemeris_receipts.json"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_corridor_receipts.md"
printf 'wrote %s\n' "$MOONCLAW_OUT/first_trusted_square_corridor_receipts.json"
printf 'wrote %s\n' "$MOONROBO_OUT/first_trusted_square_handoffs.md"
printf 'wrote %s\n' "$MOONROBO_OUT/first_trusted_square_handoffs.json"
printf 'wrote %s\n' "$UI_OUT/first_trusted_square_view.md"
printf 'wrote %s\n' "$UI_OUT/first_trusted_square_view.json"
printf 'wrote %s\n' "$RABBITA_OUT/first_trusted_square.html"
printf 'wrote %s\n' "$MOONBOOK_OUT/workspaces/first-trusted-square"
