#!/usr/bin/env python3
"""Generate the MoonBit trusted-square fixture from the checked CSV source."""

from __future__ import annotations

import csv
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "fixtures" / "first_trusted_square_dem.csv"
TARGET = ROOT / "src" / "terrain" / "generated_first_trusted_square_fixture.mbt"


def read_cells() -> tuple[str, list[list[str]]]:
    with SOURCE.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"{SOURCE} has no cells")

    tile_ids = {row["tile_id"] for row in rows}
    if len(tile_ids) != 1:
        raise SystemExit(f"{SOURCE} must contain exactly one tile_id")
    tile_id = next(iter(tile_ids))

    max_row = max(int(row["row"]) for row in rows)
    max_col = max(int(row["col"]) for row in rows)
    grid: list[list[str | None]] = [
        [None for _ in range(max_col + 1)] for _ in range(max_row + 1)
    ]
    for row in rows:
        r = int(row["row"])
        c = int(row["col"])
        if grid[r][c] is not None:
            raise SystemExit(f"duplicate cell at row={r} col={c}")
        grid[r][c] = row["elevation_m"]

    missing = [
        (r, c)
        for r, line in enumerate(grid)
        for c, value in enumerate(line)
        if value is None
    ]
    if missing:
        raise SystemExit(f"{SOURCE} is missing cells: {missing}")

    return tile_id, [[value or "0.0" for value in line] for line in grid]


def render(tile_id: str, grid: list[list[str]]) -> str:
    rows = len(grid)
    cols = len(grid[0]) if grid else 0
    literal_rows = []
    for line in grid:
        literal_rows.append("    [" + ", ".join(line) + "],")
    literal = "\n".join(literal_rows)
    return f'''///| Generated from data/fixtures/first_trusted_square_dem.csv by scripts/generate_moonmoon_fixture.py.

///|
/// Do not edit this file by hand.
fn generated_first_trusted_square_tile_id() -> String {{
  "{tile_id}"
}}

///|
fn generated_first_trusted_square_rows() -> Int {{
  {rows}
}}

///|
fn generated_first_trusted_square_cols() -> Int {{
  {cols}
}}

///|
fn generated_first_trusted_square_elevations() -> Array[Array[Double]] {{
  [
{literal}
  ]
}}
'''


def main() -> None:
    check_only = len(sys.argv) == 2 and sys.argv[1] == "--check"
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and not check_only):
        raise SystemExit("usage: generate_moonmoon_fixture.py [--check]")
    tile_id, grid = read_cells()
    content = render(tile_id, grid)
    if check_only:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            raise SystemExit(
                f"{TARGET.relative_to(ROOT)} is stale; run python3 scripts/generate_moonmoon_fixture.py"
            )
        print(f"checked {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
    else:
        TARGET.write_text(content, encoding="utf-8")
        print(f"generated {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
