#!/usr/bin/env python3
"""Generate selected-route terrain remediation evidence from checked LOLA DEM."""

from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "sources" / "lro_lola" / "first_trusted_square_northeast_stepout_dem.csv"
TARGET = ROOT / "src" / "mission" / "generated_first_trusted_square_terrain_remediation.mbt"

CELL_SIZE_M = 20.0
GRADE_LIMIT = 0.35
ROUGHNESS_LIMIT_M = 2.5
CONFIDENCE = 0.7544


def read_dem() -> list[list[float]]:
  with SOURCE.open(newline="", encoding="utf-8") as handle:
    rows = list(csv.DictReader(handle))
  if not rows:
    raise SystemExit(f"{SOURCE.relative_to(ROOT)} has no cells")
  tile_ids = {row["tile_id"] for row in rows}
  if tile_ids != {"first-trusted-square-northeast-stepout-lola"}:
    raise SystemExit(f"{SOURCE.relative_to(ROOT)} must contain the selected route tile")
  max_row = max(int(row["row"]) for row in rows)
  max_col = max(int(row["col"]) for row in rows)
  grid: list[list[float | None]] = [
    [None for _ in range(max_col + 1)] for _ in range(max_row + 1)
  ]
  for row in rows:
    r = int(row["row"])
    c = int(row["col"])
    if grid[r][c] is not None:
      raise SystemExit(f"{SOURCE.relative_to(ROOT)} repeats cell row={r} col={c}")
    grid[r][c] = float(row["elevation_m"])
  if len(grid) != 4 or any(len(row) != 4 for row in grid):
    raise SystemExit(f"{SOURCE.relative_to(ROOT)} must be a 4x4 DEM")
  missing = [
    (r, c)
    for r, row in enumerate(grid)
    for c, value in enumerate(row)
    if value is None
  ]
  if missing:
    raise SystemExit(f"{SOURCE.relative_to(ROOT)} is missing cells: {missing}")
  return [[value or 0.0 for value in row] for row in grid]


def edge_deltas(grid: list[list[float]]) -> list[float]:
  deltas: list[float] = []
  for row_index, row in enumerate(grid):
    for col_index, elevation in enumerate(row):
      if col_index + 1 < len(row):
        deltas.append(abs(elevation - row[col_index + 1]))
      if row_index + 1 < len(grid):
        deltas.append(abs(elevation - grid[row_index + 1][col_index]))
  return deltas


def model() -> dict[str, Any]:
  grid = read_dem()
  deltas = edge_deltas(grid)
  max_delta = max(deltas)
  max_grade = max_delta / CELL_SIZE_M
  roughness = sum(deltas) / len(deltas)
  blocking_edges = sum(1 for delta in deltas if delta / CELL_SIZE_M >= GRADE_LIMIT)
  grade_margin = max_grade - GRADE_LIMIT
  roughness_margin = roughness - ROUGHNESS_LIMIT_M
  decision = "Block" if grade_margin >= 0.0 or roughness_margin >= 0.0 else "Review"
  return {
    "evidence_id": "first-trusted-square-northeast-stepout-terrain-remediation-v1",
    "route_id": "northeast-stepout",
    "site_id": "first-trusted-square",
    "source_dataset_id": "lro-lola-first-trusted-square-northeast-stepout-dem-v1",
    "source_tile_id": "first-trusted-square-northeast-stepout-lola",
    "source_path": str(SOURCE.relative_to(ROOT)),
    "output_path": "output/mission/first_trusted_square_northeast_stepout_terrain_remediation.json",
    "method_id": "bounded-selected-route-terrain-remediation-v1",
    "generated_by": "scripts/generate_selected_route_terrain_remediation.py",
    "rows": len(grid),
    "cols": len(grid[0]),
    "cell_size_m": CELL_SIZE_M,
    "edge_count": len(deltas),
    "blocking_edge_count": blocking_edges,
    "max_neighbor_delta_m": max_delta,
    "max_neighbor_grade": max_grade,
    "roughness_m": roughness,
    "grade_limit": GRADE_LIMIT,
    "roughness_limit_m": ROUGHNESS_LIMIT_M,
    "grade_margin": grade_margin,
    "roughness_margin_m": roughness_margin,
    "confidence": CONFIDENCE,
    "decision": decision,
    "reasons": [
      f"bounded 4x4 LOLA route window has max neighbor grade {max_grade:.6f} against limit {GRADE_LIMIT:.6f}",
      f"average neighbor roughness is {roughness:.6f} m against limit {ROUGHNESS_LIMIT_M:.6f} m",
      f"{blocking_edges} of {len(deltas)} neighbor edges exceed the conservative grade limit",
    ],
    "next_action": "collect a wider smoother selected-route corridor or keep northeast-stepout out of MoonRobo simulation",
  }


def moon_string(value: str) -> str:
  return value.replace("\\", "\\\\").replace('"', '\\"')


def moon_number(value: int | float) -> str:
  return f"{float(value):.6f}"


def moon_decision(value: str) -> str:
  if value not in {"Allow", "Review", "Block"}:
    raise SystemExit(f"unsupported decision {value!r}")
  return value


def render() -> str:
  evidence = model()
  reason_values = [f'"{moon_string(reason)}"' for reason in evidence["reasons"]]
  reason_lines = [
    f"      {reason_values[0]},",
    f"      {reason_values[1]}, {reason_values[2]},",
  ]
  reasons = "\n".join(reason_lines)
  return f'''///| Generated from {SOURCE.relative_to(ROOT)} by scripts/generate_selected_route_terrain_remediation.py.

///|
/// Do not edit this file by hand.
fn generated_first_trusted_square_northeast_stepout_terrain_remediation() -> TerrainRemediationEvidence {{
  {{
    evidence_id: "{moon_string(evidence["evidence_id"])}",
    route_id: "{moon_string(evidence["route_id"])}",
    site_id: "{moon_string(evidence["site_id"])}",
    source_dataset_id: "{moon_string(evidence["source_dataset_id"])}",
    source_tile_id: "{moon_string(evidence["source_tile_id"])}",
    source_path: "{moon_string(evidence["source_path"])}",
    output_path: "{moon_string(evidence["output_path"])}",
    method_id: "{moon_string(evidence["method_id"])}",
    generated_by: "{moon_string(evidence["generated_by"])}",
    rows: {evidence["rows"]},
    cols: {evidence["cols"]},
    cell_size_m: {moon_number(evidence["cell_size_m"])},
    edge_count: {evidence["edge_count"]},
    blocking_edge_count: {evidence["blocking_edge_count"]},
    max_neighbor_delta_m: {moon_number(evidence["max_neighbor_delta_m"])},
    max_neighbor_grade: {moon_number(evidence["max_neighbor_grade"])},
    roughness_m: {moon_number(evidence["roughness_m"])},
    grade_limit: {moon_number(evidence["grade_limit"])},
    roughness_limit_m: {moon_number(evidence["roughness_limit_m"])},
    grade_margin: {moon_number(evidence["grade_margin"])},
    roughness_margin_m: {moon_number(evidence["roughness_margin_m"])},
    confidence: {moon_number(evidence["confidence"])},
    decision: {moon_decision(evidence["decision"])},
    reasons: [
{reasons}
    ],
    next_action: "{moon_string(evidence["next_action"])}",
  }}
}}
'''


def main() -> int:
  check_only = len(sys.argv) == 2 and sys.argv[1] == "--check"
  if len(sys.argv) > 2 or (len(sys.argv) == 2 and not check_only):
    raise SystemExit("usage: generate_selected_route_terrain_remediation.py [--check]")
  content = render()
  if check_only:
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if current != content:
      raise SystemExit(
        f"{TARGET.relative_to(ROOT)} is stale; run python3 scripts/generate_selected_route_terrain_remediation.py"
      )
    print(f"checked {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
  else:
    TARGET.write_text(content, encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
