#!/usr/bin/env python3
"""Generate the MoonBit corridor-scan table from the checked scan CSV."""

from __future__ import annotations

import csv
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "sources" / "lro_lola" / "first_trusted_square_corridor_scan_v2.csv"
TARGET = ROOT / "src" / "mission" / "generated_first_trusted_square_corridor_scan.mbt"


def decision_from_hazard(hazard: str) -> str:
    if hazard == "blocked":
        return "Block"
    if hazard == "caution":
        return "Review"
    if hazard == "clear":
        return "Allow"
    raise SystemExit(f"unsupported hazard {hazard!r}")


def read_rows() -> list[dict[str, str]]:
    with SOURCE.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"{SOURCE.relative_to(ROOT)} has no scan rows")
    ranks = [int(row["rank"]) for row in rows]
    expected = list(range(1, len(rows) + 1))
    if sorted(ranks) != expected:
        raise SystemExit(f"{SOURCE.relative_to(ROOT)} ranks must be contiguous from 1")
    return sorted(rows, key=lambda row: int(row["rank"]))


def moon_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render() -> str:
    rows = read_rows()
    entries = []
    for row in rows:
        entries.append(
            "    {\n"
            f"      scan_id: \"{moon_string(row['scan_id'])}\",\n"
            f"      window_id: \"{moon_string(row['window_id'])}\",\n"
            f"      rank: {row['rank']},\n"
            f"      row_offset: {row['row_offset']},\n"
            f"      col_offset: {row['col_offset']},\n"
            f"      source_row_start: {row['source_row_start']},\n"
            f"      source_col_start: {row['source_col_start']},\n"
            f"      min_elevation_m: {row['min_elevation_m']},\n"
            f"      max_elevation_m: {row['max_elevation_m']},\n"
            f"      elevation_range_m: {row['elevation_range_m']},\n"
            f"      max_neighbor_grade: {row['max_neighbor_grade']},\n"
            f"      roughness_m: {row['roughness_m']},\n"
            f"      decision: {decision_from_hazard(row['hazard'])},\n"
            f"      selected_route_id: \"{moon_string(row['selected_route_id'])}\",\n"
            f"      note: \"{moon_string(row['note'])}\",\n"
            "    },"
        )
    literal = "\n".join(entries)
    source_label = SOURCE.relative_to(ROOT)
    return f'''///| Generated from {source_label} by scripts/generate_corridor_scan.py.

///|
/// Do not edit this file by hand.
fn generated_first_trusted_square_corridor_scan() -> Array[CorridorScanWindow] {{
  [
{literal}
  ]
}}
'''


def main() -> None:
    check_only = len(sys.argv) == 2 and sys.argv[1] == "--check"
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and not check_only):
        raise SystemExit("usage: generate_corridor_scan.py [--check]")
    content = render()
    if check_only:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            raise SystemExit(
                f"{TARGET.relative_to(ROOT)} is stale; run python3 scripts/generate_corridor_scan.py"
            )
        print(f"checked {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
    else:
        TARGET.write_text(content, encoding="utf-8")
        print(f"generated {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
