#!/usr/bin/env python3
"""Generate the MoonBit trusted-square fixture from the checked CSV source."""

from __future__ import annotations

import csv
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "src" / "terrain" / "generated_first_trusted_square_fixture.mbt"

SOURCES = [
    (
        "first_trusted_square",
        ROOT / "data" / "sources" / "lro_lola" / "first_trusted_square_dem.csv",
    ),
    (
        "first_trusted_square_west_contour",
        ROOT
        / "data"
        / "sources"
        / "lro_lola"
        / "first_trusted_square_west_contour_dem.csv",
    ),
    (
        "first_trusted_square_north_rim",
        ROOT
        / "data"
        / "sources"
        / "lro_lola"
        / "first_trusted_square_north_rim_dem.csv",
    ),
    (
        "first_trusted_square_southwest_bypass",
        ROOT
        / "data"
        / "sources"
        / "lro_lola"
        / "first_trusted_square_southwest_bypass_dem.csv",
    ),
    (
        "first_trusted_square_south_stepout",
        ROOT
        / "data"
        / "sources"
        / "lro_lola"
        / "first_trusted_square_south_stepout_dem.csv",
    ),
]


def read_cells(source: Path) -> tuple[str, list[list[str]]]:
    with source.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"{source} has no cells")

    tile_ids = {row["tile_id"] for row in rows}
    if len(tile_ids) != 1:
        raise SystemExit(f"{source} must contain exactly one tile_id")
    tile_id = next(iter(tile_ids))

    max_row = max(int(row["row"]) for row in rows)
    max_col = max(int(row["col"]) for row in rows)
    grid: list[list[str | None]] = [
        [None for _ in range(max_col + 1)] for _ in range(max_row + 1)
    ]
    for row in rows:
        r = int(row["row"])
        c = int(row["col"])
        if grid[r][c] is not None:
            raise SystemExit(f"duplicate cell at row={r} col={c}")
        grid[r][c] = row["elevation_m"]

    missing = [
        (r, c)
        for r, line in enumerate(grid)
        for c, value in enumerate(line)
        if value is None
    ]
    if missing:
        raise SystemExit(f"{source} is missing cells: {missing}")

    return tile_id, [[value or "0.0" for value in line] for line in grid]


def render_fixture(prefix: str, source: Path, tile_id: str, grid: list[list[str]]) -> str:
    rows = len(grid)
    cols = len(grid[0]) if grid else 0
    literal_rows = []
    for line in grid:
        literal_rows.append("    [" + ", ".join(line) + "],")
    literal = "\n".join(literal_rows)
    source_label = source.relative_to(ROOT)
    signature = f"fn generated_{prefix}_elevations() -> Array[Array[Double]] {{"
    if len(signature) > 82:
        signature = (
            f"fn generated_{prefix}_elevations() -> Array[\n"
            "  Array[Double],\n"
            "] {"
        )
    return f'''///| Generated from {source_label} by scripts/generate_moonmoon_fixture.py.

///|
fn generated_{prefix}_tile_id() -> String {{
  "{tile_id}"
}}

///|
fn generated_{prefix}_rows() -> Int {{
  {rows}
}}

///|
fn generated_{prefix}_cols() -> Int {{
  {cols}
}}

///|
{signature}
  [
{literal}
  ]
}}
'''


def render() -> str:
    chunks = [
        "///| Generated by scripts/generate_moonmoon_fixture.py.",
        "///|\n\n/// Do not edit this file by hand.",
    ]
    for prefix, source in SOURCES:
        tile_id, grid = read_cells(source)
        chunks.append(render_fixture(prefix, source, tile_id, grid).rstrip())
    return "\n\n".join(chunks) + "\n"


def main() -> None:
    check_only = len(sys.argv) == 2 and sys.argv[1] == "--check"
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and not check_only):
        raise SystemExit("usage: generate_moonmoon_fixture.py [--check]")
    content = render()
    if check_only:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            raise SystemExit(
                f"{TARGET.relative_to(ROOT)} is stale; run python3 scripts/generate_moonmoon_fixture.py"
            )
        sources = ", ".join(str(source.relative_to(ROOT)) for _, source in SOURCES)
        print(f"checked {TARGET.relative_to(ROOT)} from {sources}")
    else:
        TARGET.write_text(content, encoding="utf-8")
        sources = ", ".join(str(source.relative_to(ROOT)) for _, source in SOURCES)
        print(f"generated {TARGET.relative_to(ROOT)} from {sources}")


if __name__ == "__main__":
    main()
